// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJsGGM1MeMu6EFxKloORz9isnmiS6yvM',
    appId: '1:859418833036:web:a2b730417d86e362af4ba9',
    messagingSenderId: '859418833036',
    projectId: 'driveapp-17f24',
    authDomain: 'driveapp-17f24.firebaseapp.com',
    storageBucket: 'driveapp-17f24.firebasestorage.app',
    measurementId: 'G-78MXTKZS6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO9vEXXOHOe4F3PS9-uKq3r-w7OSFFCGg',
    appId: '1:859418833036:android:36dd5703413f2c98af4ba9',
    messagingSenderId: '859418833036',
    projectId: 'driveapp-17f24',
    storageBucket: 'driveapp-17f24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ZowsHjIcYvts3IrYlReaTtctvJgIrMQ',
    appId: '1:859418833036:ios:b3ce2ddee414ee6faf4ba9',
    messagingSenderId: '859418833036',
    projectId: 'driveapp-17f24',
    storageBucket: 'driveapp-17f24.firebasestorage.app',
    iosBundleId: 'com.example.driveapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ZowsHjIcYvts3IrYlReaTtctvJgIrMQ',
    appId: '1:859418833036:ios:b3ce2ddee414ee6faf4ba9',
    messagingSenderId: '859418833036',
    projectId: 'driveapp-17f24',
    storageBucket: 'driveapp-17f24.firebasestorage.app',
    iosBundleId: 'com.example.driveapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnJsGGM1MeMu6EFxKloORz9isnmiS6yvM',
    appId: '1:859418833036:web:3e576ec4b62ad7daaf4ba9',
    messagingSenderId: '859418833036',
    projectId: 'driveapp-17f24',
    authDomain: 'driveapp-17f24.firebaseapp.com',
    storageBucket: 'driveapp-17f24.firebasestorage.app',
    measurementId: 'G-KVZZYJ0EL3',
  );
}
